# Generated by Django 3.2.4 on 2021-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_top_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bids', models.IntegerField(blank=True)),
                ('picture_link', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
