# Generated by Django 3.2.3 on 2022-01-20 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220120_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 5, 46, 21, 234656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 20, 5, 46, 21, 234656, tzinfo=utc)),
        ),
    ]
