# Generated by Django 3.2.4 on 2022-01-16 06:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210823_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_top_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='number_of_bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AUTOMOTIVE', 'Automotive'), ('ELCTRONICS', 'Electronics & Computers'), ('FASHION', 'Fashion'), ('GARDEN', 'Garden'), ('HOME', 'Home'), ('INDUSTRIAL', 'Industrial'), ('MANGA', 'Japanese manga & anime'), ('LIFESTYLE', 'Lifestyle'), ('MUSIC', 'Music & Musical Instruments'), ('SPORTS', 'Sports'), ('SOFTWARE', 'Software & Computer Games'), ('SPACESHIPS', 'Spaceships')], default='Home', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 15, 14, 2, 643692)),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 14, 2, 643692)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_on_item', to='auctions.listing'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField(max_length=1)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1024)),
                ('votes', models.IntegerField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_listing', to='auctions.listing')),
            ],
        ),
    ]
