# Generated by Django 3.2.3 on 2022-01-22 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220121_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchers', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AUTOMOTIVE', 'Automotive'), ('ELCTRONICS', 'Electronics & Computers'), ('FASHION', 'Fashion'), ('GARDEN', 'Garden'), ('HOME', 'Home'), ('INDUSTRIAL', 'Industrial'), ('MANGA', 'Japanese manga & anime'), ('LIFESTYLE', 'Lifestyle'), ('MUSIC', 'Music & Musical Instruments'), ('SPORTS', 'Sports'), ('SOFTWARE', 'Software & Computer Games'), ('SPACESHIPS', 'Spaceships')], default='HOME', max_length=128),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 12, 10, 3, 242992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 12, 10, 3, 242992, tzinfo=utc), editable=False),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
