# Generated by Django 3.2.3 on 2022-01-20 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 6, 53, 26, 535135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 20, 6, 53, 26, 535135, tzinfo=utc)),
        ),
    ]
