# Generated by Django 3.2.3 on 2022-02-04 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20220205_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watcher',
            new_name='watchlist',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 23, 27, 41, 598635, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 23, 27, 41, 598635, tzinfo=utc), editable=False),
        ),
    ]
