# Generated by Django 3.2.4 on 2022-01-16 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='auctioneer',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 15, 28, 10, 58898)),
        ),
    ]
