# Generated by Django 3.2.4 on 2022-01-16 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220116_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 6, 33, 20, 395268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 16, 6, 33, 20, 395268, tzinfo=utc)),
        ),
    ]
